# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 585c8eefed4b6f5975fda4a121595242019df78f89f47e20bcfeb6c80932ab21220bba882299fbb46be3bc190b536b0ad4ecde1e82fcfba4ab669907ecc941c5

test:
  secret_key_base: c94d010d813b02cf71d4b939878d3e2f23ca608e5d2027f81d11177644dc8381f175113dfeb25583eb91f0f5df4cf2d674707e264d3af33cde53cf9787b703fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
